baseURL = "https://buddysco.com/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "BuddysCo"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About Us"
url = "#about"
weight = 2
[[menu.main]]
name = "Download App"
url = "#contact"
weight = 3
[[menu.main]]
name = "Contact Us"
url = "contact"
weight = 4


[params]
androidAppLink = "https://play.google.com/store/apps/details?id=com.app.buddywebm"
iosAppLink = "https://www.apple.com/in/app-store/"
copyright = "All right reserved copyright © Buddysco.com 2022"
footerLogo = "images/site-navigation/buddysco-logo.webp"
logo = "images/site-navigation/buddysco-logo-horizontal.png"

[params.address]
email = "admin@buddysco.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
whatsapplink = "https://wa.me/919530077786"

# Social icons
# [[params.social]]
# icon = "fa-facebook-official"
# url = "https://www.facebook.com/"
# weight = 1
# [[params.social]]
# icon = "fa-linkedin-square"
# url = "https://www.linkedin.com/"
# weight = 2
# [[params.social]]
# icon = "fa-twitter-square"
# url = "https://twitter.com/"
# weight = 3
